const D={
  checkout:{img:'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&q=80&auto=format&fit=crop',sector:'🛍️ Comércio digital',title:'Checkout nativo <span>multi-método</span>',desc:'WooCommerce, Shopify ou integração directa via API. M-Pesa, e-Mola, mkesh, QR Code, Link, Entidade & Referência e cartão — tudo num único componente, sem enviar o cliente para fora do seu site.',methods:['M-Pesa','e-Mola','mkesh','QR Code','Link de Pagamento','Entidade & Ref.','Cartão (brevemente)'],benefits:[{i:'⚡',t:'Confirmação em < 3s',d:'Webhook entregue no instante da confirmação pela operadora, sem polling.'},{i:'📦',t:'Plugins WooCommerce & Shopify',d:'Instalação em 10 minutos — zero código necessário.'},{i:'↑',t:'+40% na conversão',d:'Checkout integrado elimina o abandono por redirect externo.'},{i:'🔒',t:'Certificado BdM',d:'Todas as transacções sob regulamentação do Banco de Moçambique.'}]},
  salary:{img:'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=1200&q=80&auto=format&fit=crop',sector:'💼 Recursos Humanos',title:'Salários e disbursement <span>em massa</span>',desc:'Processamento de salários, bónus e reembolsos para centenas de colaboradores numa única chamada à API. Relatório completo por destinatário com status individualizado.',methods:['M-Pesa','e-Mola','mkesh'],benefits:[{i:'📦',t:'Batch API',d:'JSON ou CSV com lista de beneficiários. Callback com status individual.'},{i:'📊',t:'Relatório de entrega',d:'Status por destinatário: confirmado, pendente ou falhado — com motivo.'},{i:'🔄',t:'Retry inteligente',d:'Falhas reprocessadas nos horários de maior disponibilidade de saldo.'},{i:'💬',t:'SMS de confirmação',d:'Cada colaborador recebe notificação no momento do crédito.'}]},
  'qr-pme':{img:'https://images.unsplash.com/photo-1556745753-8e78f2e3e7c1?w=1200&q=80&auto=format&fit=crop',sector:'🏪 Comércio local',title:'QR Code estático — <span>zero hardware</span>',desc:'Aceite pagamentos digitais em 2 minutos. Gere o QR no dashboard, imprima e coloque no balcão. O cliente paga com qualquer carteira — sem POS, sem contrato de aluguer.',methods:['M-Pesa','e-Mola','mkesh','QR Code'],benefits:[{i:'⏱️',t:'Setup em 2 minutos',d:'Conta aberta, QR gerado, já a receber pagamentos.'},{i:'0️⃣',t:'Zero custo de hardware',d:'Sem terminal nem mensalidade. Apenas comissão por transacção.'},{i:'📊',t:'Dashboard gratuito',d:'Acompanhe as vendas em tempo real no telemóvel ou computador.'},{i:'📱',t:'Todas as carteiras',d:'M-Pesa, e-Mola, mkesh — o cliente escolhe como pagar.'}]},
  recurring:{img:'https://images.unsplash.com/photo-1633158829585-23ba8f7c8c5d?w=1200&q=80&auto=format&fit=crop',sector:'⚙️ Utilities & Subscrições',title:'Cobranças recorrentes <span>automatizadas</span>',desc:'Configure planos mensais, quinzenais ou semanais. O sistema envia lembretes SMS, processa a cobrança e reconcilia — zero intervenção manual.',methods:['M-Pesa','e-Mola','mkesh','Entidade & Ref.'],benefits:[{i:'🔁',t:'Periodicidade flexível',d:'Diário, semanal, quinzenal, mensal — como preferir.'},{i:'🔔',t:'Lembretes SMS',d:'Aviso antes do débito para reduzir falhas por saldo insuficiente.'},{i:'📉',t:'Dunning inteligente',d:'Retry em horas de maior probabilidade de saldo disponível.'},{i:'📋',t:'Reconciliação pronta',d:'Relatórios por período prontos para auditoria contabilística.'}]},
  paylink:{img:'https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?w=1200&q=80&auto=format&fit=crop',sector:'📲 Social Commerce',title:'Links de pagamento para <span>redes sociais</span>',desc:'Venda pelo WhatsApp, Instagram e Facebook sem precisar de site. Gere um link com valor e descrição, partilhe e receba — o cliente paga como preferir.',methods:['M-Pesa','e-Mola','mkesh','QR Code'],benefits:[{i:'🔗',t:'URL personalizável',d:'Defina valor, produto e prazo. URL curto pronto a partilhar.'},{i:'📱',t:'Qualquer canal',d:'WhatsApp, Telegram, Facebook, SMS — onde estiver o cliente.'},{i:'📊',t:'Rastreio de conversão',d:'Veja quantos abriram e quantos pagaram.'},{i:'⚡',t:'Confirmação imediata',d:'Notificação assim que o pagamento é confirmado.'}]},
  school:{img:'https://images.unsplash.com/photo-1523050854058-8df90910b78b?w=1200&q=80&auto=format&fit=crop',sector:'🎓 Instituições de ensino',title:'Propinas e inscrições <span>digitais</span>',desc:'Escolas e universidades recebem propinas via mobile money. Referência única por aluno e reconciliação automática — a tesouraria só confere.',methods:['M-Pesa','e-Mola','mkesh','Entidade & Ref.'],benefits:[{i:'📋',t:'Referência por aluno',d:'Cada pagamento associado ao número de aluno automaticamente.'},{i:'🔔',t:'Notificação dupla',d:'Encarregado e tesouraria recebem alerta no momento do pagamento.'},{i:'📊',t:'Relatórios financeiros',d:'Exportação mensal e anual para a direcção financeira.'},{i:'🏦',t:'Multi-conta',d:'Contas separadas por departamento, turno ou nível de ensino.'}]},
  marketplace:{img:'https://images.unsplash.com/photo-1553729459-afe8e5e2f0a2?w=1200&q=80&auto=format&fit=crop',sector:'🛍️ Marketplace',title:'Split de pagamentos <span>inteligente</span>',desc:'Para marketplaces com múltiplos vendedores. Defina percentagens, valores fixos e distribua fundos automaticamente em tempo real.',methods:['M-Pesa','e-Mola','mkesh','QR Code','Link de Pagamento'],benefits:[{i:'✂️',t:'Split configurável',d:'Percentagem ou valor fixo por categoria ou vendedor.'},{i:'⏱️',t:'Liquidação instantânea',d:'Fundos chegam ao vendedor no momento do pagamento.'},{i:'🧾',t:'Faturação automática',d:'Recibos e facturas gerados automaticamente por transacção.'},{i:'📈',t:'Dashboard por vendedor',d:'Cada vendedor vê as suas vendas, saques e histórico.'}]},
  health:{img:'https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?w=1200&q=80&auto=format&fit=crop',sector:'🏥 Saúde',title:'Clínicas e farmácias <span>sem hardware</span>',desc:'O paciente digitaliza um QR ou recebe um link. Recibo digital enviado automaticamente — a clínica só precisa de um telemóvel.',methods:['M-Pesa','e-Mola','mkesh','QR Code','Link de Pagamento'],benefits:[{i:'🧾',t:'Recibo digital automático',d:'PDF enviado por SMS imediatamente após cada pagamento.'},{i:'📱',t:'Sem equipamento',d:'Um telemóvel para confirmar o pagamento — mais nada.'},{i:'💊',t:'Integração com sistemas',d:'API para conectar ao software de gestão da clínica.'},{i:'🔒',t:'Dados protegidos',d:'Conformidade com normas de protecção de dados em Moçambique.'}]},
  refund:{img:'https://images.unsplash.com/photo-1589758438368-0a2d2e7a1f4e?w=1200&q=80&auto=format&fit=crop',sector:'↩️ Reembolsos',title:'Reembolsos programáticos <span>em segundos</span>',desc:'Processe devoluções via API ou dashboard. O valor retorna à carteira do cliente em menos de 30 segundos, com rastreabilidade total.',methods:['M-Pesa','e-Mola','mkesh'],benefits:[{i:'⚡',t:'< 30s por reembolso',d:'Do pedido à confirmação de crédito na carteira do cliente.'},{i:'🔗',t:'Ligado à transacção',d:'Cada reembolso rastreia a transacção de origem.'},{i:'📊',t:'Dashboard de devoluções',d:'Reembolsos, motivos e impacto na receita em tempo real.'},{i:'🤝',t:'Fidelização',d:'Clientes com reembolsos rápidos têm 3x mais probabilidade de recomprar.'}]},
  insurance:{img:'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&q=80&auto=format&fit=crop',sector:'🛡️ Sector segurador',title:'Prémios e indemnizações <span>via mobile</span>',desc:'Cobre prémios recorrentes e paga sinistros directamente na carteira do segurado — rápido, rastreável e sem burocracia bancária.',methods:['M-Pesa','e-Mola','mkesh'],benefits:[{i:'🔁',t:'Prémios recorrentes',d:'Cobrança diária, semanal ou mensal com gestão de inadimplência.'},{i:'⚡',t:'Indemnização instantânea',d:'Pagamento de sinistros em segundos após aprovação.'},{i:'📑',t:'Rastreabilidade total',d:'Cada transacção registada para auditoria e compliance.'},{i:'🌍',t:'Alcance rural',d:'Segurados sem conta bancária através das carteiras móveis.'}]},
  microfinance:{img:'https://images.unsplash.com/photo-1593672715438-88a70629dc2c?w=1200&q=80&auto=format&fit=crop',sector:'🌍 Inclusão financeira',title:'Microcrédito e <span>inclusão financeira</span>',desc:'IMFs, cooperativas e ONGs chegam a comunidades rurais sem banco. Desembolso de empréstimos e recolha de reembolsos via mobile money.',methods:['M-Pesa','e-Mola','mkesh'],benefits:[{i:'🏘️',t:'Alcance rural',d:'Sem conta bancária — qualquer carteira móvel é suficiente.'},{i:'📦',t:'Desembolso em massa',d:'Liberte múltiplos empréstimos numa única operação batch.'},{i:'🔄',t:'Recolha de reembolsos',d:'Cobranças automáticas conforme o calendário acordado.'},{i:'📊',t:'Relatórios de carteira',d:'Taxas de reembolso, inadimplência e impacto social.'}]},
  events:{img:'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&q=80&auto=format&fit=crop',sector:'🎟️ Eventos & Entretenimento',title:'Bilhetes digitais e <span>venda online</span>',desc:'Venda bilhetes via link nas redes sociais ou QR Code na porta. Controlo de entradas com validação digital — sem papel, sem filas.',methods:['M-Pesa','e-Mola','mkesh','QR Code','Link de Pagamento'],benefits:[{i:'🔗',t:'Venda antecipada via link',d:'Partilhe nas redes e receba antes do evento.'},{i:'📲',t:'Bilhete digital por SMS',d:'QR code enviado após pagamento. Validado na entrada.'},{i:'📊',t:'Controlo de capacidade',d:'Painel em tempo real com bilhetes vendidos e disponíveis.'},{i:'↩️',t:'Reembolsos automáticos',d:'Em caso de cancelamento, devolução automática aos compradores.'}]},
  transport:{img:'https://images.unsplash.com/photo-1570125909232-eb263c4e4c3e?w=1200&q=80&auto=format&fit=crop',sector:'🚌 Transportes',title:'Bilhetes e passes <span>digitais</span>',desc:'Venda bilhetes individuais e passes mensais via mobile money. Validação por QR no embarque e relatórios de receita por rota.',methods:['M-Pesa','e-Mola','mkesh','QR Code'],benefits:[{i:'🎟️',t:'Bilhete por QR Code',d:'Comprado no telemóvel, validado na entrada. Sem papel, sem troco.'},{i:'🔁',t:'Passes mensais automáticos',d:'Renovação automática com desconto para fidelização.'},{i:'📊',t:'Gestão de rotas',d:'Receita por rota, hora e veículo em tempo real.'},{i:'👥',t:'Tarifas especiais',d:'Preços diferenciados para estudantes, idosos e pessoas com deficiência.'}]},
  api:{img:'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200&q=80&auto=format&fit=crop',sector:'👨‍💻 API & Integração',title:'API REST com <span>SDKs prontos</span>',desc:'Documentação completa, sandbox gratuito e SDKs para Node.js, Python, PHP e Dart. Da integração ao go-live em 48 horas com suporte técnico dedicado.',methods:['REST API','Node.js SDK','Python SDK','PHP SDK','Dart SDK','Sandbox'],benefits:[{i:'📚',t:'Documentação completa',d:'Referência com exemplos em várias linguagens e guias passo a passo.'},{i:'🧪',t:'Sandbox gratuito',d:'Teste todos os fluxos sem dinheiro real. Logs detalhados por request.'},{i:'⚡',t:'48h go-live',d:'Suporte técnico dedicado para integração em menos de 2 dias úteis.'},{i:'🔑',t:'Chaves API em segundos',d:'Sandbox e live geradas no dashboard sem aprovação manual.'}]},
  webhook:{img:'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&q=80&auto=format&fit=crop',sector:'🔗 Webhooks',title:'Notificações em tempo real <span>via Webhooks</span>',desc:'Configure endpoints HTTP para receber eventos de pagamento. Retry automático com backoff exponencial e logs completos de entrega.',methods:['HTTPS','JSON','HMAC-SHA256'],benefits:[{i:'⚡',t:'Entrega em < 1s',d:'Evento disparado imediatamente após confirmação da operadora.'},{i:'🔄',t:'Retry com backoff',d:'Falhas reprocessadas com intervalos crescentes automaticamente.'},{i:'📋',t:'Logs de entrega',d:'Histórico completo de tentativas, respostas e status.'},{i:'🔒',t:'Assinatura HMAC',d:'Payload assinado com HMAC-SHA256 para verificação de autenticidade.'}]},
  fraud:{img:'https://images.unsplash.com/photo-1633265486501-0cf524a07213?w=1200&q=80&auto=format&fit=crop',sector:'🔒 Segurança & Compliance',title:'Anti-fraude, KYC e <span>compliance BdM</span>',desc:'Motor de detecção de fraude com regras configuráveis, validação KYC no onboarding e relatórios AML automáticos para o Banco de Moçambique.',methods:['Fraud API','KYC','AML','BdM Compliance'],benefits:[{i:'🔍',t:'Análise comportamental',d:'Padrões suspeitos identificados em tempo real com bloqueio automático.'},{i:'🪪',t:'KYC integrado',d:'Validação de identidade no fluxo de onboarding via API.'},{i:'📑',t:'Relatórios AML',d:'Relatórios de monitorização prontos para submissão regulatória.'},{i:'⚙️',t:'Regras personalizáveis',d:'Configure limites, whitelist, blacklist e lógica de risco.'}]},
  reconciliation:{img:'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=1200&q=80&auto=format&fit=crop',sector:'📊 Reconciliação & Relatórios',title:'Reconciliação automática <span>e relatórios</span>',desc:'Exporte transacções em tempo real para o seu ERP ou sistema contabilístico. CSV, JSON e XML com filtros avançados por data, método e status.',methods:['CSV','JSON','XML','Webhooks','API'],benefits:[{i:'🔄',t:'Exportação agendada',d:'Configure exports automáticos para o seu sistema contabilístico.'},{i:'📊',t:'Dashboard financeiro',d:'Receita, comissões e liquidações consolidadas em tempo real.'},{i:'🔌',t:'Integração ERP',d:'Conectores para SAP, Sage e Primavera incluídos.'},{i:'📅',t:'Relatórios por período',d:'Diário, mensal, anual — filtre por método, status e conta.'}]},
  testing:{img:'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=1200&q=80&auto=format&fit=crop',sector:'🧪 Sandbox',title:'Ambiente de testes <span>completo e gratuito</span>',desc:'Simule todos os cenários — pagamentos, falhas, timeouts, reembolsos, webhooks — sem dinheiro real. Ambiente completamente isolado de produção.',methods:['Sandbox API','Simulação de cenários','Test webhooks'],benefits:[{i:'🎭',t:'Force qualquer cenário',d:'Sucesso, saldo insuficiente, timeout, falha — tudo simulável.'},{i:'📋',t:'Logs detalhados',d:'Request e response completos para facilitar o debugging.'},{i:'🔑',t:'Chaves isoladas',d:'Ambiente separado da produção — sem risco.'},{i:'🆓',t:'100% gratuito',d:'Sem limite de chamadas durante o desenvolvimento.'}]},
  multitenancy:{img:'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&q=80&auto=format&fit=crop',sector:'🏗️ Banking-as-a-Service',title:'Plataformas white-label <span>e multi-tenant</span>',desc:'Construa a sua própria fintech sobre a infraestrutura iMaliway. Sub-contas, permissões granulares e relatórios consolidados — com a sua marca.',methods:['REST API','Sub-contas','White-label','BaaS'],benefits:[{i:'🏷️',t:'White-label completo',d:'A sua marca e domínio. O cliente final nunca vê o nome iMaliway.'},{i:'👥',t:'Sub-contas geridas',d:'Crie, configure e suspenda contas de clientes via API.'},{i:'🔐',t:'Permissões granulares',d:'Controlo total sobre o que cada sub-conta pode fazer.'},{i:'📊',t:'Relatórios consolidados',d:'Vista agregada de toda a rede de sub-contas na conta master.'}]},
};

function switchTab(btn,tab){
  document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));
  btn.classList.add('active');
  document.querySelectorAll('.cards-panel').forEach(p=>p.classList.remove('active'));
  const p=document.getElementById('panel-'+tab);
  p.classList.add('active');
  p.querySelectorAll('.use-card').forEach((c,i)=>{c.style.animation='none';void c.offsetWidth;c.style.animation=`cIn .6s cubic-bezier(.22,1,.36,1) ${i*0.06+0.02}s both`;});
  setTimeout(observeReveal,60);
}
function openModal(id){
  const d=D[id];if(!d)return;
  document.getElementById('modal-img').src=d.img;
  document.getElementById('modal-sector').textContent=d.sector;
  document.getElementById('modal-title').innerHTML=d.title;
  document.getElementById('modal-desc').textContent=d.desc;
  document.getElementById('modal-methods').innerHTML=d.methods.map(m=>`<span class="method-chip">${m}</span>`).join('');
  document.getElementById('modal-benefits').innerHTML=d.benefits.map(b=>`<div class="benefit"><div class="benefit-icon">${b.i}</div><div><h4>${b.t}</h4><p>${b.d}</p></div></div>`).join('');
  document.getElementById('modal-backdrop').classList.add('open');
  document.body.style.overflow='hidden';
}
function closeModal(){document.getElementById('modal-backdrop').classList.remove('open');document.body.style.overflow='';}
function handleBackdropClick(e){if(e.target===document.getElementById('modal-backdrop'))closeModal();}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});
function toggleTheme(){const h=document.documentElement;h.setAttribute('data-theme',h.getAttribute('data-theme')==='dark'?'light':'dark');}
function observeReveal(){
  const els=document.querySelectorAll('.reveal:not(.visible)');
  const obs=new IntersectionObserver(en=>{en.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target);}});},{threshold:.08});
  els.forEach(el=>obs.observe(el));
}
observeReveal();